language: node_js
node_js:
- lts/boron
- node
sudo: false
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: H/7AECCmUL2yWlMWKOSo3uuR1a2/WshUbonWXXNHnYMHUqqLow2gNrEnIVkqoOpSDkom9jQixy2q/1XkIKBRXGdBsxkeiSKVKdZE+EUsbVTgzBhScEcLStqDJo+k8Fz/oduqGiToMWPUV7kQ2W685u/oCyHmWqlPSKjNZC9tNuw=
  file:
    - "iso-639-2.js"
    - "iso-639-2.min.js"
  on:
    tags: true
